### PR TITLE
Port it to run on macOS and Fix a little typo.

### PR DESCRIPTION
**Pull request by Evsio0n**

### CODE REVIEW

**Comment by Evsio0n** [comment]
As you can see , It can be run on bsd like os (macOS) now.

**Comment by Evsio0n** [comment]
@ShanQincheng Requesting review.

**Comment by ShanQincheng** [comment]
Thanks a lot. I haven't noticed your commits until tonight and sorry for your waiting.

**Comment by ShanQincheng** [comment]
> @ShanQincheng Requesting review.

Thanks a lot. I didn't notice your commits until tonight and sorry for your waiting.

**Pull request merged**
